name: taoss3932_web_site
description: five_bell_hyun portfolio

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+42

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.6
  carousel_slider: ^5.0.0
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: notosans
      fonts:
        - asset: assets/fonts/notosans.ttf